image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t my-image:latest .
  
test:
  stage: test
  script:
    - docker run --rm my-image:latest sh -c "ls -l /app && cd bin && ls"







