
stages:
  - cleanup
  - build
  - test
  - documentation
variables:
  ANT_HOME: "/home/dosi/Téléchargements/apache-ant-1.9.6"  # Set the path to your Ant installation

before_script:
  - export PATH="$ANT_HOME/bin:$PATH"
  - echo "Starting the CI/CD pipeline..."
  - export VERSION="v$(date +'%Y%m%d')"
  - ant -version  # Check Ant installation

build:
  stage: build
  script:
    - echo "Building the project..."
    - ant compile

test:
  stage: test
  script:
    - echo "Running tests..."
    - ant test
  artifacts:
    paths:
      - bin/test-results/**/*
      - test-reports/**/*

documentation:
  stage: documentation
  script:
    - echo "Generating documentation..."
    - ant javadoc
  artifacts:
    paths:
      - javadoc/**/*

clean:
  stage: cleanup
  script:
    - echo "Cleaning up..."
    - ant clean





