image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t my-image:latest .
    - docker run my-image:latest
    - mkdir -p output


  
   







