stages:
  - clean
  - retrieve
  - compile
  - compile-test
  - javadoc
  - dist
  - test
variables:
  ANT_HOME: "/home/dosi/Téléchargements/apache-ant-1.9.6/bin/ant"  # Set the path to your Ant installation

before_script:
  - export PATH="$ANT_HOME/bin:$PATH"
  - echo "Starting the CI/CD pipeline..."
  - export VERSION="v$(date +'%Y%m%d')"
  - ant -version  # Check Ant installation

clean-job:
  stage: clean
  script:
    - ant clean
  only:
    - main
    - dev
  tags:
    - ysf_hr

retrieve-job:
  stage: retrieve
  script:
    - ant retrieve
  needs:
    - clean-job
  only:
    - main
    - dev
  tags:
    - ysf_hr

compile-job:
  stage: compile
  script:
    - ant compile
  needs:
    - retrieve-job
  only:
    - main
    - dev
  tags:
    - ysf_hr
  artifacts:
    paths:
      - bin/
    expire_in: 1 week

# Job pour compiler les tests unitaires
compile-test-job:
  stage: compile-test
  script:
    - ant compile-test
  needs:
    - compile-job
  artifacts:
    paths:
      - bin/test/
    expire_in: 1 week





javadoc-job:
  stage: javadoc
  script:
    - ant javadoc
  needs:
    - compile-job
  only:
    - main
    - dev
  tags:
    - ysf_hr
  artifacts:
    paths:
      - javadoc/
    expire_in: 1 week

dist-job:
  stage: dist
  script:
    - ant dist
  needs:
    - javadoc-job
  only:
    - main
    - dev
  tags:
    - ysf_hr
  artifacts:
    paths:
      - bin/Tetris.jar
    expire_in: 1 week