stages:
  - build
  - test
  - docs
  - dist

variables:
  ANT_HOME: "/home/dosi/Téléchargements/apache-ant-1.9.6/"  # Set the path to your Ant installation

before_script:
  - export PATH="$ANT_HOME/bin:$PATH"
  - echo "Starting the CI/CD pipeline..."
  - export VERSION="v$(date +'%Y%m%d')"
  - ant -version  # Check Ant installatio

build:
  stage: build
  script:
    - echo "Cleaning up workspace..."
    - rm -rf bin/* dist/*
    - echo "Building the project with Ant..."
    - ant -d compile
  only:
    - main
    - dev
  tags:
    - ysf_hr

test:
  stage: test
  script:
    - echo "Running tests with Ant..."
    - ant test  # Assuming you have a test target in your build file
  only:
    - main
    - dev
  tags:
    - ysf_hr
  dependencies:
    - build

javadoc:
  stage: docs
  script:
    - echo "Generating Javadoc with Ant..."
    - ant javadoc
  only:
    - main
    - dev
  tags:
    - ysf_hr
  dependencies:
    - build
  artifacts:
    paths:
      - javadoc/
    expire_in: 1 week

dist:
  stage: dist
  script:
    - echo "Packaging the project into a JAR file with Ant..."
    - ant dist
  only:
    - main
    - dev
  tags:
    - ysf_hr
  dependencies:
    - build  
  artifacts:
    paths:
      - dist/
    expire_in: 1 week


